spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authorization
    username: postgres
    password: thirumal
server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://thirumal:thirumal@localhost:8761/eureka/
google:
  recaptcha:
    key:
      site: 6LcTncEkAAAAACymEdK_QG-
      secret: 6LcTncEkAAAAAOmE5T8ec
      threshold: 0.5
notification: 
  email:
    sender: no-reply@enkindletech.com
  sms: 
    sender: ENKTPL